### ISSUE TITLE
지금 문장 만들기 / 듣고 이해하기 버튼을 눌렀을때 동일한 페이지로 이동하고 있는 것 같아요~

### ISSUE THREAD

**Issue by Kihyun92** [CodeSoom/project-react-2-gringrape#111]
![image](https://user-images.githubusercontent.com/35797540/101283801-2a9d6880-3820-11eb-937e-733a0e5de88c.png)

https://www.ddomal.com/ 에서 확인했습니다.

**Comment by gringrape** [comment]
@Kihyun92 완성이 안되어서 연결을 안했는데
버튼도 같이 안보이게 해야할 것 같습니다 ㅎㅎ

**Comment by gringrape** [comment]
다시 연결했습니다 ㅎㅎ #115
