### ISSUE TITLE
페이지에서 새로고침을 하면 에러가 발생합니다.

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-react-2-gringrape#56]
https://codesoom.github.io/project-react-2-gringrape/sentence 이 페이지에서 새로고침을 하면 다음과 같이 에러가 발생합니다.

![image](https://user-images.githubusercontent.com/14071105/100115321-b70d6a00-2eb5-11eb-8e8c-fa3641c9310d.png)

**Comment by gringrape** [comment]
엇.. 감사합니다! 바로 수정하겠습니다.
