### ISSUE TITLE
사용자에게 안내하는 문구를 수정하면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-react-2-gringrape#57]
![image](https://user-images.githubusercontent.com/14071105/100115499-f045da00-2eb5-11eb-8d1a-5910c9f31114.png)

문장을 입력하는 것 아니라 제시어로 문장을 만들어서 소리내어 말해주세요 더 명확한 문장으로 바꾸는건 어떨까요?

**Comment by gringrape** [comment]
넵 명확하게 고쳐보겠습니다 :)
