### ISSUE TITLE
현재 소리를 입력하고 있다는 피드백을 얻을 수 있을까요?

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-react-2-gringrape#58]
소리를 입력하고 있는지 잘 파악이 안되서 내가 잘 말하고 있는건지 모르겠습니다.

내가 입력을 잘 하고 있는지 보여주는건 어떨까요? 예를들어 디스코드에서는 다음과 같이 내가 말하고 있을 땐 초록색으로 표시를 해줍니다

![image](https://user-images.githubusercontent.com/14071105/100115742-3a2ec000-2eb6-11eb-9878-2cc942de076e.png)

**Comment by gringrape** [comment]
아 마이크가 켜질때가 아니라. 실제로 음성이 입력될때의 피드백이군요 
한참 작업하다가 잘못된걸 깨달았습니다
이부분도 작업 가능할 것 같습니다 ㅎ

**Comment by gringrape** [comment]
이 부분은 작업하면 정말 좋겠네요. 일어나서 바로 해보겠습니다.

**Comment by gringrape** [comment]
이거 구현하다가 하루를 통째로 바쳤습니다.  허허...

**Comment by gringrape** [comment]
#64
