### ISSUE TITLE
문장을 얘기했을 때 피드백이 없습니다.

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-react-2-gringrape#68]
![image](https://user-images.githubusercontent.com/14071105/100365878-63308b80-3043-11eb-9410-fdb3d11d004b.png)

간단하게라도 내가 말한 문장안에 제시어가 잘 들어가 있다면 띵동!하고 다음으로 넘어가는 그런 피드백이 있다면 어떨까요?

**Comment by gringrape** [comment]
엇 소리를 생각못했네요.
제시어를 하이라이트 해주자고만 생각했는데,
효과음을 넣어보겠습니다! :)

**Comment by hannut91** [comment]
효과음은 ㅎㅎ 중요한건 아니었어요. 피드백이 있으면 좋겠습니다

**Comment by gringrape** [comment]
ㅋㅋ 그렇군요 어떤식으로든 피드백을 추가해보겠습니다 ㅎㅎ

**Comment by gringrape** [comment]
![image](https://user-images.githubusercontent.com/53764714/100411521-5d738e00-30b5-11eb-8e81-b1503f8b75ca.png)

일단 어떻게든 피드백을 줘보자 해서 파란색으로 강조만 했는데
생각보다 잘어울리는것 같습니다 ㅋㅋ 

포함안됐을때랑 소리나는 것도 구현해보고 느낌을 보겠습니다!

**Comment by gringrape** [comment]
#80 띵동 한번 추가해봤습니다

**Comment by gringrape** [comment]
#82 제시어가 없을때의 피드백도 줘봤는데 여러가지 해봐도 통 신통치가 않네요..
계속 고민해보겠습니다.

**Comment by hannut91** [comment]
크으 ㅎㅎ 좋습니다!
